# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gDZ2goevGGidHf-29keY7SfLvQNGrSkI
"""

!pip install pandas matplotlib seaborn

from google.colab import files


uploaded = files.upload()


filename = list(uploaded.keys())[0]
print(f"Uploaded file: {filename}")


df = pd.read_csv(filename)


df.head()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_csv("data.csv")


df.head()

print(df.columns)

df = pd.read_csv("data.csv", skiprows=3)
print(df.head())

print(df.columns)

df.rename(columns={"Unnamed: 0": "Country Name",
                   "Unnamed: 1": "Country Code",
                   "Unnamed: 2": "Indicator Name",
                   "Unnamed: 3": "Indicator Code"}, inplace=True)

df_melted = df.melt(id_vars=["Country Name", "Country Code", "Indicator Name", "Indicator Code"],
                    var_name="Year", value_name="Population")

print(df_melted.head())

print(df.columns)

print(df.head(10))

df = pd.read_csv("data.csv", header=0)

print(df.head())
print(df.columns)

df = pd.read_csv("data.csv", header=3)

print(df.head())
print(df.columns)

df_melted = df.melt(id_vars=["Country Name", "Country Code", "Indicator Name", "Indicator Code"],
                    var_name="Year", value_name="Population")

df_melted["Year"] = pd.to_numeric(df_melted["Year"], errors="coerce")
df_melted["Population"] = pd.to_numeric(df_melted["Population"], errors="coerce")

print(df.columns)

df = pd.read_csv("data.csv", header=3)

print(df.head())
print(df.columns)

df.columns = df.iloc[0]
df = df[1:].reset_index(drop=True)

print(df.head())
print(df.columns)

df_melted = df.melt(id_vars=["Country Name", "Country Code", "Indicator Name", "Indicator Code"],
                    var_name="Year", value_name="Population")

df_melted["Year"] = pd.to_numeric(df_melted["Year"], errors="coerce")
df_melted["Population"] = pd.to_numeric(df_melted["Population"], errors="coerce")

import matplotlib.pyplot as plt

df_india = df_melted[df_melted["Country Name"] == "India"]

plt.figure(figsize=(12, 6))
plt.bar(df_india["Year"], df_india["Population"], color="skyblue")
plt.xlabel("Year")
plt.ylabel("Population")
plt.title("Population Growth of India Over Time")
plt.xticks(rotation=45)
plt.show()